import type { Category, HoardItem, Rarity, Status } from '../types/content';
import { createDefaultItem } from './mapping';

const baseLinks = (slug: string) => [
  { label: 'Design Notes', url: `https://example.com/${slug}/notes`, kind: 'doc' as const },
  { label: 'Changelog', url: `https://example.com/${slug}/changelog`, kind: 'doc' as const },
];

const coreItems: HoardItem[] = [
  createDefaultItem({
    id: 'dragon-treasury',
    title: 'Dragon Treasury',
    shortSummary: 'Interactive cave archive experience.',
    longDescription:
      'A playful, atmospheric archive where every creation is represented as a physical treasure object. The goal is tactile narrative browsing rather than practical portfolio indexing.',
    category: 'projects',
    rarity: 'legendary',
    status: 'in-progress',
    year: 2026,
    tags: ['interactive', 'pixi', 'matter', 'archive'],
    techStack: ['React', 'TypeScript', 'PixiJS', 'Matter.js', 'GSAP'],
    repoUrl: 'https://github.com/azuredreams/DragonTreasury',
    links: [
      { label: 'Repository', url: 'https://github.com/azuredreams/DragonTreasury', kind: 'repo' },
      { label: 'Vision Brief', url: 'https://example.com/dragon-treasury/brief', kind: 'doc' },
    ],
    images: [{ src: '/assets/ui/placeholder-hero.svg', alt: 'Glowing dragon cave concept art' }],
    whyItMatters: 'This is the personal mythology layer over years of practical building work.',
    featured: true,
    dragonAffinity: 0.98,
    visualHint: 'Radiant amber artifact with engraved scales and drifting embers.',
  }),
  createDefaultItem({
    id: 'auric-ledger',
    title: 'Auric Ledger',
    shortSummary: 'Revenue + operations dashboard prototype.',
    longDescription:
      'A productized operations ledger that merged transactions, subscriptions, and runway projections into one narrative timeline view.',
    category: 'products',
    rarity: 'rare',
    status: 'prototype',
    year: 2023,
    tags: ['fintech', 'visualization', 'ops'],
    techStack: ['React', 'Node', 'PostgreSQL'],
    links: baseLinks('auric-ledger'),
    repoUrl: 'https://github.com/example/auric-ledger',
    liveUrl: 'https://example.com/auric-ledger',
    whyItMatters: 'First serious attempt at shipping a tool with a clear pricing model.',
    featured: true,
    dragonAffinity: 0.62,
    visualHint: 'A faceted citrine gem with etched ledger marks.',
  }),
  createDefaultItem({
    id: 'wyrm-shell-os',
    title: 'WyrmShell OS Layer',
    shortSummary: 'Composable AI automation shell.',
    longDescription:
      'An automation system for chaining prompt workflows, file transforms, and scheduling into reproducible scripts.',
    category: 'systems',
    rarity: 'epic',
    status: 'in-progress',
    year: 2025,
    tags: ['automation', 'ai', 'workflow'],
    techStack: ['TypeScript', 'Python', 'CLI'],
    links: baseLinks('wyrmshell'),
    notes: 'Strong candidate to split into standalone modules.',
    whyItMatters: 'Raised the baseline quality and speed of everyday development operations.',
    featured: true,
    dragonAffinity: 0.9,
    visualHint: 'Teal arcane crystal with runic pulse rings.',
  }),
  createDefaultItem({
    id: 'emberforge-print-rig',
    title: 'Emberforge Print Rig',
    shortSummary: 'Physical build automation station for rapid prototyping.',
    longDescription:
      'A modular 3D printing and electronics bench setup with sensor logging and enclosure tests for iterative hardware experiments.',
    category: 'physical-builds',
    rarity: 'epic',
    status: 'in-progress',
    year: 2024,
    tags: ['hardware', '3d-printing', 'sensors'],
    techStack: ['Fusion 360', 'ESP32', 'Python'],
    links: baseLinks('emberforge-rig'),
    images: [{ src: '/assets/ui/placeholder-build.svg', alt: 'Metal idol with gears and light channels' }],
    notes: 'Cabin airflow still needs optimization for long runs.',
    featured: true,
    dragonAffinity: 0.74,
    visualHint: 'Forged brass idol with moving gear halo.',
  }),
  createDefaultItem({
    id: 'moonglass-notes',
    title: 'Moonglass Notes Vault',
    shortSummary: 'Cross-linked note and article repository.',
    longDescription:
      'A personal archive system for design fragments, writing notes, and architecture memos, indexed with topic and era metadata.',
    category: 'notes',
    rarity: 'uncommon',
    status: 'shipped',
    year: 2022,
    tags: ['writing', 'notes', 'knowledge'],
    techStack: ['Markdown', 'Static Site', 'Search'],
    links: baseLinks('moonglass-notes'),
    whyItMatters: 'Captured years of loose thinking into reusable knowledge.',
    visualHint: 'Sealed scroll capsule with wax sigils.',
  }),
  createDefaultItem({
    id: 'cauldron-labs-ai',
    title: 'Cauldron Labs Assistant',
    shortSummary: 'AI toolchain for operational tasks.',
    longDescription:
      'A set of agentic helpers for processing checklists, generating docs, and syncing project status with lightweight prompts.',
    category: 'ai-tools',
    rarity: 'rare',
    status: 'in-progress',
    year: 2026,
    tags: ['agents', 'ai', 'ops'],
    techStack: ['OpenAI API', 'TypeScript', 'Python'],
    links: baseLinks('cauldron-labs-ai'),
    featured: true,
    visualHint: 'Floating crystal spindle with teal sparks.',
    dragonAffinity: 0.88,
  }),
  createDefaultItem({
    id: 'sunken-inventory',
    title: 'Sunken Inventory Experiment',
    shortSummary: 'Abandoned inventory simulation game prototype.',
    longDescription:
      'A logistics puzzle wrapped in mythic worldbuilding. The simulation worked, but visual direction and retention loops never landed.',
    category: 'abandoned',
    rarity: 'rare',
    status: 'abandoned',
    year: 2019,
    tags: ['game', 'simulation', 'abandoned'],
    techStack: ['Unity', 'C#'],
    links: baseLinks('sunken-inventory'),
    notes: 'Learned a lot about balancing complexity against clarity.',
    visualHint: 'Cracked relic medallion with ember cracks.',
  }),
  createDefaultItem({
    id: 'obsidian-router',
    title: 'Obsidian Router Core',
    shortSummary: 'Edge service router with policy experiments.',
    longDescription:
      'A routing core that focused on deterministic behavior and explicit policy declarations for production infrastructure.',
    category: 'systems',
    rarity: 'rare',
    status: 'archived',
    year: 2021,
    tags: ['networking', 'infra', 'edge'],
    techStack: ['Go', 'Redis', 'Docker'],
    links: baseLinks('obsidian-router'),
    visualHint: 'Hexagonal rune crystal with obsidian core.',
  }),
  createDefaultItem({
    id: 'citadel-market',
    title: 'Citadel Market',
    shortSummary: 'Marketplace experiment with creator storefronts.',
    longDescription:
      'An attempt to build a curated digital goods marketplace with storytelling-focused product pages and quality scoring.',
    category: 'products',
    rarity: 'epic',
    status: 'paused',
    year: 2020,
    tags: ['marketplace', 'commerce', 'product'],
    techStack: ['Next.js', 'Stripe', 'Prisma'],
    links: baseLinks('citadel-market'),
    whyItMatters: 'First full-stack project with payment and moderation workflows.',
    featured: true,
    visualHint: 'Deep sapphire gem with engraved trade sigils.',
  }),
  createDefaultItem({
    id: 'vault-weather-index',
    title: 'Vault Weather Index',
    shortSummary: 'Visualization experiment for environmental telemetry.',
    longDescription:
      'A charming weather telemetry map rendered with hand-crafted visual motifs and ambient animation layers.',
    category: 'experiments',
    rarity: 'uncommon',
    status: 'archived',
    year: 2018,
    tags: ['data-viz', 'weather', 'maps'],
    techStack: ['D3', 'Canvas'],
    links: baseLinks('vault-weather-index'),
    visualHint: 'Weathered bronze coin with wave carvings.',
  }),
  createDefaultItem({
    id: 'forge-memoir',
    title: 'Forge Memoir',
    shortSummary: 'Favorite reflective writing project.',
    longDescription:
      'A personal set of essays about technical growth, decisions, reversals, and what was learned from each season of building.',
    category: 'favorite',
    rarity: 'legendary',
    status: 'shipped',
    year: 2024,
    tags: ['writing', 'reflection', 'favorite'],
    techStack: ['MDX', 'Static Site'],
    links: baseLinks('forge-memoir'),
    whyItMatters: 'Codified personal engineering values and design principles.',
    featured: true,
    visualHint: 'Relic tablet with molten-gold calligraphy.',
    dragonAffinity: 0.95,
  }),
  createDefaultItem({
    id: 'relic-sentinel',
    title: 'Relic Sentinel',
    shortSummary: 'Watchtower automation and anomaly watcher.',
    longDescription:
      'A low-noise monitoring stack that grouped alert patterns and surfaced narrative summaries instead of raw noise.',
    category: 'projects',
    rarity: 'epic',
    status: 'shipped',
    year: 2025,
    tags: ['monitoring', 'alerts', 'automation'],
    techStack: ['TypeScript', 'Sentry API', 'Cloudflare'],
    links: baseLinks('relic-sentinel'),
    visualHint: 'Tall carved artifact with ember watch-eyes.',
    featured: true,
  }),
  createDefaultItem({
    id: 'chronicle-shard',
    title: 'Chronicle Shard',
    shortSummary: 'Prototype timeline storytelling engine.',
    longDescription:
      'A narrative time-scrubber that arranged artifacts by era and emotional tone for story-first browsing.',
    category: 'prototypes',
    rarity: 'rare',
    status: 'prototype',
    year: 2023,
    tags: ['timeline', 'storytelling', 'ux'],
    techStack: ['React', 'Framer Motion'],
    links: baseLinks('chronicle-shard'),
    visualHint: 'Segmented metal idol with rotating timeline rings.',
  }),
  createDefaultItem({
    id: 'ember-crown-secret',
    title: 'The Ember Crown',
    shortSummary: 'A hidden relic unlocked by earning the dragon’s trust.',
    longDescription:
      'An intentionally hidden legendary relic that symbolizes curiosity and persistence. It appears only when the dragon is engaged repeatedly.',
    category: 'relics',
    rarity: 'legendary',
    status: 'archived',
    year: 2017,
    tags: ['secret', 'easter-egg', 'legend'],
    techStack: ['Mystery'],
    links: [{ label: 'Whispered Lore', url: 'https://example.com/ember-crown/lore', kind: 'doc' }],
    whyItMatters: 'A reminder that delight is a product feature, not a garnish.',
    visualHint: 'Burning crown relic with prismatic embers.',
    dragonAffinity: 1,
    hiddenUntilUnlocked: true,
    featured: true,
  }),
];

const experimentNames = [
  'Pocket Automaton',
  'Lantern Queue',
  'Moss Compiler',
  'Rune Planner',
  'Signal Orchard',
  'Marble Sandbox',
  'Echo Atlas',
  'Thread Forge',
  'Nimbus Lens',
  'Quartz Relay',
  'Ink Cartographer',
  'Ivory Patchbay',
  'Pyre Palette',
  'Rook Scheduler',
  'Flux Almanac',
  'Gleam Diffuser',
  'Aether Ledger',
  'Basilisk Prompt Lab',
  'Cinder Maze',
  'Whisper Sorter',
  'Iron Bloom',
  'Lattice Dreamer',
  'Cobalt Draft',
  'Vault Pebble',
  'Opal Surveyor',
  'Rune Critic',
  'Tidal Script',
  'Aurora Capsule',
  'Mirror Foundry',
  'Signal Prism',
  'Brass Scribe',
  'Fable Node',
];

const rarityCycle: Rarity[] = ['common', 'uncommon', 'rare', 'common', 'rare', 'epic'];
const statusCycle: Status[] = ['prototype', 'archived', 'in-progress', 'paused', 'shipped', 'abandoned'];
const categoryCycle: Category[] = [
  'experiments',
  'projects',
  'prototypes',
  'notes',
  'systems',
  'ai-tools',
  'abandoned',
];

const generatedItems: HoardItem[] = experimentNames.map((name, index) => {
  const year = 2012 + (index % 14);
  const rarity = rarityCycle[index % rarityCycle.length];
  const status = statusCycle[index % statusCycle.length];
  const category = categoryCycle[index % categoryCycle.length];
  const slug = name.toLowerCase().replace(/\s+/g, '-');

  return createDefaultItem({
    id: `seed-${slug}`,
    title: name,
    shortSummary: `${category.replace('-', ' ')} entry from the vault archive.`,
    longDescription:
      'Seed placeholder entry designed for realistic filtering, arrangement, and interaction testing. Replace with real project details as needed.',
    category,
    rarity,
    status,
    year,
    tags: [category, rarity, year.toString(), 'seed'],
    techStack: ['TypeScript', 'Static Data'],
    links: [{ label: 'Placeholder Notes', url: `https://example.com/${slug}`, kind: 'doc' }],
    notes: 'Generated seed entry; safe to overwrite with real content.',
    visualHint: 'Generated relic texture with subtle engravings.',
    featured: index % 9 === 0,
    dragonAffinity: 0.25 + ((index % 7) * 0.08),
  });
});

export const seedHoardItems: HoardItem[] = [...coreItems, ...generatedItems];
